# Activación de Hilos Virtuales (Project Loom)
spring.threads.virtual.enabled=true

# Observabilidad: Health Checks
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
